language: c
os:
- linux
dist:
- trusty
compiler:
- gcc
script: make hello_world


before_deploy:
- openssl aes-256-cbc -K $encrypted_0ac51efc6383_key -iv $encrypted_0ac51efc6383_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

addons:
  ssh_known_hosts: aur.archlinux.org


# deploy:
#   - echo "Cd to tmp"
#   - cd /tmp
#   - echo "Cloning aur pkg"
#   - git clone git+ssh://aur.archlinux.org/yuview-git.git
#   - cd yuview-git

#   # get the new version:
#   - echo "Cloning YUView"
#   - git clone https://github.com/IENT/YUView
#   - cd YUView
#   - new_version=$(printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)")
#   - echo ${new_version}
#   - cd ..

#   - echo "Updated version in files"
#   - sed -i "s/pkgver=.*$/pkgver=${new_version}/" PKGBUILD
#   - sed -i "s/pkgver = .*$/pkgver = ${new_version}/" .SRCINFO

#   - echo "commiting and pushing new version"
#   - git add -u
#   - git commit -m "updated package version"
#   - git push


      
deploy:
- provider: script
  skip_cleanup: true
  script: ls updateYUViewPKGBUILDVersion.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true  
  script: updateYUViewPKGBUILDVersion.sh
  on:
    branch: master