language: c
os:
- linux
dist:
- trusty
compiler:
- gcc
script: make hello_world
deploy:
before_deploy:
- openssl aes-256-cbc -K $encrypted_0ac51efc6383_key -iv $encrypted_0ac51efc6383_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

addons:
  ssh_known_hosts: aur.archlinux.org

deploy:
  - provider: script
    script: updateYUViewPKGBUILDVersion.sh
    on:
      branch: master